services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${FLASK_PORT:-5000}:${FLASK_PORT:-5000}"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL_DOCKER}
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - req-mng-network

  postgres:
    image: postgres:13-alpine
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - req-mng-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reqmng"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  req-mng-network:
    driver: bridge
