services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://reqmng:reqmng@postgres:5432/reqmng
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - req-mng-network

  postgres:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=reqmng
      - POSTGRES_USER=reqmng
      - POSTGRES_PASSWORD=reqmng
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - req-mng-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U reqmng"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  req-mng-network:
    driver: bridge
