"""add_verification_method_column

Revision ID: 5a76c0a0a02e
Revises: cdbf8fc6bb6e
Create Date: 2025-07-25 16:01:34.025149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a76c0a0a02e'
down_revision: Union[str, Sequence[str], None] = 'cdbf8fc6bb6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requirements', sa.Column('verification_method', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requirements', 'verification_method')
    # ### end Alembic commands ###
